### ISSUE TITLE
adding separate frontend spa (react/vue/etc) 

### ISSUE THREAD

**Issue by wiktorcie** [nickjj/docker-django-example#13]
Hi,
Would using django as api and adding new container for spa be possible/easy with this setup?

**Comment by nickjj** [comment]
You could use DRF if you wanted to, nothing would need to change container wise. The front-end stuff is already in their own containers using esbuild and tailwind. Using React or whatever you want to use would be a matter of installing React and using it.

**Comment by wiktorcie** [comment]
But to run in SPA mode with something like `yarn dev` or `npm start`  I need to make some specific changes, right? Otherwise it will be SSR with django.

(I have in mind vuejs/quasar.dev)

**Comment by nickjj** [comment]
What is SPA mode? Would React or whatever tool you use require running its own dedicated tool instead of just esbuild? Normally esbuild would watch your JS for changes and reload things for you.

**Comment by wiktorcie** [comment]
yep I had some misconception about that sorry man! I will integrate quasar/vue soon and see how it works for me.

**Comment by nickjj** [comment]
It's all good, let us know how it goes.

If you end up having to make a number of changes feel free to open a https://github.com/nickjj/docker-django-example/discussions outlining the steps you took, that would be very helpful for others and much appreciated.
