### ISSUE TITLE
[Error: EACCES: permission denied, mkdir '/app/public/css']

### ISSUE THREAD

**Issue by jsballesterosm** [nickjj/docker-django-example#9]
![Captura de Pantalla 2021-12-16 a la(s) 6 45 08 p m](https://user-images.githubusercontent.com/78027649/146465286-b66c2b5c-f784-4de7-a23b-649ddbc9abef.png)

help me !

**Comment by nickjj** [comment]
What OS are you using?

**Comment by jsballesterosm** [comment]
![Captura de Pantalla 2021-12-16 a la(s) 6 49 03 p m](https://user-images.githubusercontent.com/78027649/146465610-9e094b89-420a-4a42-a51e-c3c0af557d58.png)


Centos 7

**Comment by nickjj** [comment]
What's the output of running `id`?

**Comment by nickjj** [comment]
Going to close this as it's been a few months with no follow up.

**Comment by nickjj** [comment]
This is fixed in: https://github.com/nickjj/docker-django-example/commit/b269057cd7df996ffa479d76e3b441435c3af5d9
